### ISSUE TITLE
Failures in the "Build Windows Native Image" CI step 

### ISSUE THREAD

**Issue by blickly** [google/closure-compiler-npm#306]
The last two CI runs (4 hours and 11 hours ago) have failed for the "Build Windows Native Image" step failed with the same error message:
```
 $ node build-image.js
  google-closure-compiler-windows building image
Error: spawn EINVAL
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at spawn (node:child_process:761:9)
    at D:\a\closure-compiler-npm\closure-compiler-npm\build-scripts\run-command.js:53:23
    at new Promise (<anonymous>)
    at runCommand (D:\a\closure-compiler-npm\closure-compiler-npm\build-scripts\run-command.js:49:19)
    at Object.<anonymous> (D:\a\closure-compiler-npm\closure-compiler-npm\build-scripts\graal.js:60:1)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12) {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'spawn'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

It seems many of these CI steps are a bit flaky, so hopefully that's the case, but filing this issue to track just in case.

**Comment by blickly** [comment]
Unfortunately, the looks to not be flaky, as there have now been a few more failures with the same message.  Unfortunately, I don't think many of the capacity to investigate (or a windows machine for that matter).

@ChadKillingsworth, do you have an idea what could be going wrong here?

**Comment by ChadKillingsworth** [comment]
I can definitely take a look. Diagnosing problems like this on windows builds is super challenging.

**Comment by ChadKillingsworth** [comment]
Oh this may be a security change by Node: https://nodejs.org/en/blog/vulnerability/april-2024-security-releases-2
